// Restore specific entities from a weak-entity snapshot JSON (taken before a
// remediation run). Use to roll back entities that regressed.
//
// Usage:
//   pnpm tsx scripts/restore-snapshot.ts --file <snapshot.json> --slugs a,b,c

import "../lib/env";
import { readFileSync } from "node:fs";
import { eq, sql } from "drizzle-orm";

import { db } from "@/lib/db";
import {
  entities,
  entityAliases,
  entityClaimedCitations,
  entityClaims,
  entityTopics,
} from "@/lib/db/schema";
import { withRetry } from "@/lib/db/retry";

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i !== -1 ? process.argv[i + 1] : undefined;
}

interface Snap {
  id: string;
  slug: string;
  canonical_name: string;
  disambiguator: string | null;
  entity_type: string;
  status: string;
  short_description: string;
  summary: string;
  narrative: string;
  structured_facts: unknown;
  key_dates: unknown;
  coords: unknown;
  generator_model: string;
  verifier_model: string | null;
  consensus_score: number;
  disagreement_notes: unknown;
  claim_factuality_score: number | null;
  embedding: string | null;
  aliases: string[] | null;
  topics: string[] | null;
  citations:
    | Array<{
        claim_excerpt: string;
        claimed_source: string;
        claimed_url: string | null;
        claimed_author: string | null;
        claim_kind: string;
        verified_by_second_model: boolean;
      }>
    | null;
}

async function main(): Promise<void> {
  const file = arg("--file");
  const slugsArg = arg("--slugs");
  if (!file || !slugsArg) {
    console.error("usage: --file <snapshot.json> --slugs a,b,c");
    process.exit(1);
  }
  const slugs = new Set(slugsArg.split(",").map((s) => s.trim()));
  const snap: Snap[] = JSON.parse(readFileSync(file, "utf8"));
  const targets = snap.filter((e) => slugs.has(e.slug));

  if (targets.length !== slugs.size) {
    const found = new Set(targets.map((t) => t.slug));
    const missing = [...slugs].filter((s) => !found.has(s));
    console.error(`snapshot missing slugs: ${missing.join(", ")}`);
  }

  for (const e of targets) {
    await withRetry("restore", () =>
      db.transaction(async (tx) => {
        await tx
          .update(entities)
          .set({
            canonicalName: e.canonical_name,
            disambiguator: e.disambiguator,
            entityType: e.entity_type,
            status: e.status,
            shortDescription: e.short_description,
            summary: e.summary,
            narrative: e.narrative,
            structuredFacts: e.structured_facts as Record<string, unknown>,
            keyDates: e.key_dates as object[],
            coords: e.coords as object | null,
            generatorModel: e.generator_model,
            verifierModel: e.verifier_model,
            consensusScore: e.consensus_score,
            disagreementNotes: e.disagreement_notes as object[],
            claimFactualityScore: e.claim_factuality_score,
            // Restore the original embedding via a raw cast.
            embedding: e.embedding
              ? (sql`${e.embedding}::vector` as unknown as number[])
              : null,
            updatedAt: new Date(),
          })
          .where(eq(entities.id, e.id));

        // Replace side rows with the snapshot's.
        await tx.delete(entityAliases).where(eq(entityAliases.entityId, e.id));
        if (e.aliases?.length) {
          await tx
            .insert(entityAliases)
            .values(e.aliases.map((alias) => ({ entityId: e.id, alias })))
            .onConflictDoNothing();
        }
        await tx.delete(entityTopics).where(eq(entityTopics.entityId, e.id));
        if (e.topics?.length) {
          await tx
            .insert(entityTopics)
            .values(e.topics.map((topic) => ({ entityId: e.id, topic })))
            .onConflictDoNothing();
        }
        await tx
          .delete(entityClaimedCitations)
          .where(eq(entityClaimedCitations.entityId, e.id));
        if (e.citations?.length) {
          await tx.insert(entityClaimedCitations).values(
            e.citations.map((c) => ({
              entityId: e.id,
              claimExcerpt: c.claim_excerpt,
              claimedSource: c.claimed_source,
              claimedUrl: c.claimed_url,
              claimedAuthor: c.claimed_author,
              claimKind: c.claim_kind,
              verifiedBySecondModel: c.verified_by_second_model,
            })),
          );
        }

        // The post-remediation per-claim rows describe the discarded
        // narrative — drop them. (claim_factuality_score is restored above;
        // per-claim detail can be regenerated by score-claims later.)
        await tx.delete(entityClaims).where(eq(entityClaims.entityId, e.id));
      }),
    );
    console.log(
      `restored ${e.canonical_name} → factuality ${(
        (e.claim_factuality_score ?? 0) * 100
      ).toFixed(0)}%`,
    );
  }
  console.log(`\nrestored ${targets.length} entit${targets.length === 1 ? "y" : "ies"}.`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
